services:
  - type: web
    name: vibetec-app
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://vibetec-app.onrender.com
    healthCheckPath: /
